service:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - HOMEPAGE_VAR_PIHOLE_APIKEY="SET_LATER"
    volumes:
      - ~/homepage_config:/app/config
    ports:
      - 3000:3000
    restart: unless-stopped
